using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace EmployeeAudit.Migrations
{
    /// <inheritdoc />
    public partial class Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Cities",
                columns: table => new
                {
                    city_name = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    state_name = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cities", x => x.city_name);
                });

            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    country_name = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    country_short_name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    country_phone_code = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.country_name);
                });

            migrationBuilder.CreateTable(
                name: "Employees",
                columns: table => new
                {
                    EmployeeId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Employees", x => x.EmployeeId);
                });

            migrationBuilder.CreateTable(
                name: "Events",
                columns: table => new
                {
                    EventId = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    LastUpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    EventType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    User = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JsonData = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Events", x => x.EventId);
                });

            migrationBuilder.CreateTable(
                name: "States",
                columns: table => new
                {
                    state_name = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    country_name = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_States", x => x.state_name);
                });

            migrationBuilder.CreateTable(
                name: "Address",
                columns: table => new
                {
                    AddressId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    City = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    State = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZipCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Country = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EmployeeId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Address", x => x.AddressId);
                    table.ForeignKey(
                        name: "FK_Address_Employees_EmployeeId",
                        column: x => x.EmployeeId,
                        principalTable: "Employees",
                        principalColumn: "EmployeeId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "city_name", "state_name" },
                values: new object[,]
                {
                    { "Achalpur", "Maharashtra" },
                    { "Achampet", "Telangana" },
                    { "Adilabad", "Telangana" },
                    { "Aheri", "Maharashtra" },
                    { "Ahmadnagar Cantonment", "Maharashtra" },
                    { "Ahmadpur", "Maharashtra" },
                    { "Ahmednagar", "Maharashtra" },
                    { "Ajra", "Maharashtra" },
                    { "Akalkot", "Maharashtra" },
                    { "Akkalkuwa", "Maharashtra" },
                    { "Akola", "Maharashtra" },
                    { "Akot", "Maharashtra" },
                    { "Alandi", "Maharashtra" },
                    { "Alibag", "Maharashtra" },
                    { "Allapalli", "Maharashtra" },
                    { "Alore", "Maharashtra" },
                    { "Amalner", "Maharashtra" },
                    { "Ambad", "Maharashtra" },
                    { "Ambajogai", "Maharashtra" },
                    { "Ambernath", "Maharashtra" },
                    { "Ambivali Tarf Wankhal", "Maharashtra" },
                    { "Amgaon", "Maharashtra" },
                    { "Amravati", "Maharashtra" },
                    { "Anjangaon", "Maharashtra" },
                    { "Armoor", "Telangana" },
                    { "Arvi", "Maharashtra" },
                    { "Ashta", "Maharashtra" },
                    { "Ashti", "Maharashtra" },
                    { "Asifabad", "Telangana" },
                    { "Aurangabad", "Maharashtra" },
                    { "Aurangabad Cantonment", "Maharashtra" },
                    { "Ausa", "Maharashtra" },
                    { "Babhulgaon", "Maharashtra" },
                    { "Badepally", "Telangana" },
                    { "Badlapur", "Maharashtra" },
                    { "Balapur", "Maharashtra" },
                    { "Ballarpur", "Maharashtra" },
                    { "Banswada", "Telangana" },
                    { "Baramati", "Maharashtra" },
                    { "Barshi", "Maharashtra" },
                    { "Basmat", "Maharashtra" },
                    { "Beed", "Maharashtra" },
                    { "Bellampalli", "Telangana" },
                    { "Bhadrachalam", "Telangana" },
                    { "Bhadravati", "Maharashtra" },
                    { "Bhagur", "Maharashtra" },
                    { "Bhainsa", "Telangana" },
                    { "Bhandara", "Maharashtra" },
                    { "Bhigvan", "Maharashtra" },
                    { "Bhingar", "Maharashtra" },
                    { "Bhiwandi", "Maharashtra" },
                    { "Bhokhardan", "Maharashtra" },
                    { "Bhongir", "Telangana" },
                    { "Bhor", "Maharashtra" },
                    { "Bhosari", "Maharashtra" },
                    { "Bhum", "Maharashtra" },
                    { "Bhupalpally", "Telangana" },
                    { "Bhusawal", "Maharashtra" },
                    { "Bid", "Maharashtra" },
                    { "Biloli", "Maharashtra" },
                    { "Birwadi", "Maharashtra" },
                    { "Bodhan", "Telangana" },
                    { "Boisar", "Maharashtra" },
                    { "Bollaram", "Telangana" },
                    { "Bop Khel", "Maharashtra" },
                    { "Brahmapuri", "Maharashtra" },
                    { "Budhgaon", "Maharashtra" },
                    { "Buldana", "Maharashtra" },
                    { "Buldhana", "Maharashtra" },
                    { "Buti Bori", "Maharashtra" },
                    { "Chakan", "Maharashtra" },
                    { "Chalisgaon", "Maharashtra" },
                    { "Chandrapur", "Maharashtra" },
                    { "Chandur", "Maharashtra" },
                    { "Chandur Bazar", "Maharashtra" },
                    { "Chandvad", "Maharashtra" },
                    { "Chicholi", "Maharashtra" },
                    { "Chikhala", "Maharashtra" },
                    { "Chikhaldara", "Maharashtra" },
                    { "Chikhli", "Maharashtra" },
                    { "Chinchani", "Maharashtra" },
                    { "Chinchwad", "Maharashtra" },
                    { "Chiplun", "Maharashtra" },
                    { "Chopda", "Maharashtra" },
                    { "Dabhol", "Maharashtra" },
                    { "Dahanu", "Maharashtra" },
                    { "Daharu", "Maharashtra" },
                    { "Dapoli Camp", "Maharashtra" },
                    { "Darwha", "Maharashtra" },
                    { "Daryapur Banosa", "Maharashtra" },
                    { "Dattapur Dhamangaon", "Maharashtra" },
                    { "Daund", "Maharashtra" },
                    { "Davlameti", "Maharashtra" },
                    { "Deglur", "Maharashtra" },
                    { "Dehu", "Maharashtra" },
                    { "Dehu Road", "Maharashtra" },
                    { "Deolali", "Maharashtra" },
                    { "Deolali Pravara", "Maharashtra" },
                    { "Deoli", "Maharashtra" },
                    { "Desaiganj", "Maharashtra" },
                    { "Deulgaon Raja", "Maharashtra" },
                    { "Devarkonda", "Telangana" },
                    { "Dewhadi", "Maharashtra" },
                    { "Dhadgaon", "Maharashtra" },
                    { "Dhaka", "Maharashtra" },
                    { "Dhamangaon", "Maharashtra" },
                    { "Dhanki", "Maharashtra" },
                    { "Dharangaon", "Maharashtra" },
                    { "Dharmabad", "Maharashtra" },
                    { "Dharur", "Maharashtra" },
                    { "Dhatau", "Maharashtra" },
                    { "Dhule", "Maharashtra" },
                    { "Digdoh", "Maharashtra" },
                    { "Digras", "Maharashtra" },
                    { "Dombivli", "Maharashtra" },
                    { "Dondaicha Warwade", "Maharashtra" },
                    { "Dudhani", "Maharashtra" },
                    { "Durgapur", "Maharashtra" },
                    { "Dyane", "Maharashtra" },
                    { "Edandol", "Maharashtra" },
                    { "Eklahare", "Maharashtra" },
                    { "Faizpur", "Maharashtra" },
                    { "Farooqnagar", "Telangana" },
                    { "Fekari", "Maharashtra" },
                    { "Gadchiroli", "Maharashtra" },
                    { "Gadhinglaj", "Maharashtra" },
                    { "Gadwal", "Telangana" },
                    { "Gajwel", "Telangana" },
                    { "Ganeshpur", "Maharashtra" },
                    { "Gangakher", "Maharashtra" },
                    { "Gangapur", "Maharashtra" },
                    { "Georai", "Maharashtra" },
                    { "Gevrai", "Maharashtra" },
                    { "Ghatanji", "Maharashtra" },
                    { "Ghatkesar", "Telangana" },
                    { "Ghoti Budruk", "Maharashtra" },
                    { "Ghugus", "Maharashtra" },
                    { "Ghulewadi", "Maharashtra" },
                    { "Gondiya", "Maharashtra" },
                    { "Guhagar", "Maharashtra" },
                    { "Hadgaon", "Maharashtra" },
                    { "Hinganghat", "Maharashtra" },
                    { "Hingoli", "Maharashtra" },
                    { "Hupari", "Maharashtra" },
                    { "Hyderabad", "Telangana" },
                    { "Ichalkaranji", "Maharashtra" },
                    { "Igatpuri", "Maharashtra" },
                    { "Indapur", "Maharashtra" },
                    { "Islampur", "Maharashtra" },
                    { "Jagtial", "Telangana" },
                    { "Jaisinghpur", "Maharashtra" },
                    { "Jalgaon", "Maharashtra" },
                    { "Jalgaon Cantonment", "Maharashtra" },
                    { "Jalna", "Maharashtra" },
                    { "Jamkhed", "Maharashtra" },
                    { "Jangaon", "Telangana" },
                    { "Jawhar", "Maharashtra" },
                    { "Jaysingpur", "Maharashtra" },
                    { "Jejuri", "Maharashtra" },
                    { "Jintur", "Maharashtra" },
                    { "Junnar", "Maharashtra" },
                    { "Kabnur", "Maharashtra" },
                    { "Kagal", "Maharashtra" },
                    { "Kagaznagar", "Telangana" },
                    { "Kalamb", "Maharashtra" },
                    { "Kalamboli", "Maharashtra" },
                    { "Kalameshwar", "Maharashtra" },
                    { "Kalamnuri", "Maharashtra" },
                    { "Kalmeshwar", "Maharashtra" },
                    { "Kalundre", "Maharashtra" },
                    { "Kalwakurthy", "Telangana" },
                    { "Kalyan", "Maharashtra" },
                    { "Kamareddy", "Telangana" },
                    { "Kamthi", "Maharashtra" },
                    { "Kandari", "Maharashtra" },
                    { "Kandhar", "Maharashtra" },
                    { "Kandri", "Maharashtra" },
                    { "Kandri II", "Maharashtra" },
                    { "Kankavli", "Maharashtra" },
                    { "Kannad", "Maharashtra" },
                    { "Karad", "Maharashtra" },
                    { "Karanja", "Maharashtra" },
                    { "Karanje Tarf", "Maharashtra" },
                    { "Karimnagar", "Telangana" },
                    { "Karivali", "Maharashtra" },
                    { "Karjat", "Maharashtra" },
                    { "Karmala", "Maharashtra" },
                    { "Kasara", "Maharashtra" },
                    { "Katai", "Maharashtra" },
                    { "Katkar", "Maharashtra" },
                    { "Katol", "Maharashtra" },
                    { "Kegaon", "Maharashtra" },
                    { "Khadki", "Maharashtra" },
                    { "Khamgaon", "Maharashtra" },
                    { "Khammam", "Telangana" },
                    { "Khapa", "Maharashtra" },
                    { "Kharadi", "Maharashtra" },
                    { "Kharakvasla", "Maharashtra" },
                    { "Kharsundi", "Maharashtra" },
                    { "Kheda", "Maharashtra" },
                    { "Khedgaon", "Maharashtra" },
                    { "Kherdi", "Maharashtra" },
                    { "Khopoli", "Maharashtra" },
                    { "Khuldabad", "Maharashtra" },
                    { "Kinwat", "Maharashtra" },
                    { "Kodada", "Telangana" },
                    { "Kodoli", "Maharashtra" },
                    { "Kolhapur", "Maharashtra" },
                    { "Kon", "Maharashtra" },
                    { "Kondalwadi", "Maharashtra" },
                    { "Kondhali", "Maharashtra" },
                    { "Kondumal", "Maharashtra" },
                    { "Kopargaon", "Maharashtra" },
                    { "Kopharad", "Maharashtra" },
                    { "Koradi", "Maharashtra" },
                    { "Koratla", "Telangana" },
                    { "Koregaon", "Maharashtra" },
                    { "Korochi", "Maharashtra" },
                    { "Kottagudem", "Telangana" },
                    { "Kudal", "Maharashtra" },
                    { "Kuhi", "Maharashtra" },
                    { "Kukatpally", "Maharashtra" },
                    { "Kundaim", "Maharashtra" },
                    { "Kundalwadi", "Maharashtra" },
                    { "Kurduvadi", "Maharashtra" },
                    { "Kusgaon", "Maharashtra" },
                    { "Kyathampalle", "Telangana" },
                    { "Lakhandur", "Maharashtra" },
                    { "Lakheri", "Maharashtra" },
                    { "Lanja", "Maharashtra" },
                    { "Lasalgaon", "Maharashtra" },
                    { "Latur", "Maharashtra" },
                    { "Loha", "Maharashtra" },
                    { "Lohegaon", "Maharashtra" },
                    { "Lonar", "Maharashtra" },
                    { "Lonavala", "Maharashtra" },
                    { "Madhavnagar", "Maharashtra" },
                    { "Madhira", "Telangana" },
                    { "Mahabaleshwar", "Maharashtra" },
                    { "Mahabubabad", "Telangana" },
                    { "Mahad", "Maharashtra" },
                    { "Mahadula", "Maharashtra" },
                    { "Mahbubnagar", "Telangana" },
                    { "Maindargi", "Maharashtra" },
                    { "Majalgaon", "Maharashtra" },
                    { "Malegaon", "Maharashtra" },
                    { "Malgaon", "Maharashtra" },
                    { "Malkapur", "Maharashtra" },
                    { "Malwan", "Maharashtra" },
                    { "Mancherial", "Telangana" },
                    { "Mandamarri", "Telangana" },
                    { "Mangalvedhe", "Maharashtra" },
                    { "Mangrul Dastgir", "Maharashtra" },
                    { "Mangrulpir", "Maharashtra" },
                    { "Manjlegaon", "Maharashtra" },
                    { "Manmad", "Maharashtra" },
                    { "Manor", "Maharashtra" },
                    { "Mansar", "Maharashtra" },
                    { "Manuguru", "Telangana" },
                    { "Manwath", "Maharashtra" },
                    { "Maregaon", "Maharashtra" },
                    { "Medak", "Telangana" },
                    { "Medchal", "Telangana" },
                    { "Mehkar", "Maharashtra" },
                    { "Mhasla", "Maharashtra" },
                    { "Mhaswad", "Maharashtra" },
                    { "Mira Bhayandar", "Maharashtra" },
                    { "Miraj", "Maharashtra" },
                    { "Miryalaguda", "Telangana" },
                    { "Mohpa", "Maharashtra" },
                    { "Mohpada", "Maharashtra" },
                    { "Morshi", "Maharashtra" },
                    { "Mowad", "Maharashtra" },
                    { "Mudkhed", "Maharashtra" },
                    { "Mukhed", "Maharashtra" },
                    { "Mul", "Maharashtra" },
                    { "Mumbai", "Maharashtra" },
                    { "Murbad", "Maharashtra" },
                    { "Murgud", "Maharashtra" },
                    { "Murud", "Maharashtra" },
                    { "Murum", "Maharashtra" },
                    { "Muth", "Maharashtra" },
                    { "Mutha", "Maharashtra" },
                    { "Mutha Kalmath", "Maharashtra" },
                    { "Nagapur", "Maharashtra" },
                    { "Nagar Karnul", "Telangana" },
                    { "Nagardeole", "Maharashtra" },
                    { "Nagothane", "Maharashtra" },
                    { "Nagpur", "Maharashtra" },
                    { "Nakoda", "Maharashtra" },
                    { "Nakrekal", "Telangana" },
                    { "Nalasopara", "Maharashtra" },
                    { "Naldurg", "Maharashtra" },
                    { "Nalgonda", "Telangana" },
                    { "Nanded", "Maharashtra" },
                    { "Nandgaon", "Maharashtra" },
                    { "Nandura", "Maharashtra" },
                    { "Nandurbar", "Maharashtra" },
                    { "Narayanpet", "Telangana" },
                    { "Narkhed", "Maharashtra" },
                    { "Narsampet", "Telangana" },
                    { "Nashik", "Maharashtra" },
                    { "Navi Mumbai", "Maharashtra" },
                    { "Navi Mumbai Panvel", "Maharashtra" },
                    { "Navi Mumbai Uran", "Maharashtra" },
                    { "Nawapur", "Maharashtra" },
                    { "Neral", "Maharashtra" },
                    { "Nilanga", "Maharashtra" },
                    { "Nimbhore", "Maharashtra" },
                    { "Nirmal", "Telangana" },
                    { "Nizamabad", "Telangana" },
                    { "Ojhar", "Maharashtra" },
                    { "Osmanabad", "Maharashtra" },
                    { "Ozar", "Maharashtra" },
                    { "Pachgaon", "Maharashtra" },
                    { "Pachora", "Maharashtra" },
                    { "Padagha", "Maharashtra" },
                    { "Paithan", "Maharashtra" },
                    { "Palghar", "Maharashtra" },
                    { "Pali", "Maharashtra" },
                    { "Palwancha", "Telangana" },
                    { "Panchgani", "Maharashtra" },
                    { "Pandhakawada", "Maharashtra" },
                    { "Pandharpur", "Maharashtra" },
                    { "Panhala", "Maharashtra" },
                    { "Panvel", "Maharashtra" },
                    { "Paranda", "Maharashtra" },
                    { "Parbhani", "Maharashtra" },
                    { "Parli", "Maharashtra" },
                    { "Parola", "Maharashtra" },
                    { "Partur", "Maharashtra" },
                    { "Parvatsar", "Maharashtra" },
                    { "Patan", "Maharashtra" },
                    { "Pathardi", "Maharashtra" },
                    { "Pathri", "Maharashtra" },
                    { "Patur", "Maharashtra" },
                    { "Pauni", "Maharashtra" },
                    { "Peddapalli", "Telangana" },
                    { "Pen", "Maharashtra" },
                    { "Phaltan", "Maharashtra" },
                    { "Pimpri", "Maharashtra" },
                    { "Pimpri Chinchwad", "Maharashtra" },
                    { "Pipri", "Maharashtra" },
                    { "Pira Behere", "Maharashtra" },
                    { "Poladpur", "Maharashtra" },
                    { "Pulgaon", "Maharashtra" },
                    { "Pune", "Maharashtra" },
                    { "Pune Cantonment", "Maharashtra" },
                    { "Pune Division", "Maharashtra" },
                    { "Pusad", "Maharashtra" },
                    { "Rahimatpur", "Maharashtra" },
                    { "Rahta Pimplas", "Maharashtra" },
                    { "Rahuri", "Maharashtra" },
                    { "Rahuri Factory", "Maharashtra" },
                    { "Raigarh", "Maharashtra" },
                    { "Raigarh Fort", "Maharashtra" },
                    { "Rajapur", "Maharashtra" },
                    { "Rajgurunagar", "Maharashtra" },
                    { "Rajur", "Maharashtra" },
                    { "Rajura", "Maharashtra" },
                    { "Ramagundam", "Telangana" },
                    { "Ramtek", "Maharashtra" },
                    { "Ranga Reddy district", "Telangana" },
                    { "Ratnagiri", "Maharashtra" },
                    { "Ravalgaon", "Maharashtra" },
                    { "Raver", "Maharashtra" },
                    { "Risod", "Maharashtra" },
                    { "Roha", "Maharashtra" },
                    { "Roha Ashtami", "Maharashtra" },
                    { "Rui", "Maharashtra" },
                    { "Sadasivpet", "Telangana" },
                    { "Sailu", "Maharashtra" },
                    { "Sakoli", "Maharashtra" },
                    { "Sakri", "Maharashtra" },
                    { "Salekasa", "Maharashtra" },
                    { "Salgare", "Maharashtra" },
                    { "Samudrapur", "Maharashtra" },
                    { "Sangamner", "Maharashtra" },
                    { "Sangareddy", "Telangana" },
                    { "Sangli", "Maharashtra" },
                    { "Sangole", "Maharashtra" },
                    { "Sarapaka", "Telangana" },
                    { "Sasti", "Maharashtra" },
                    { "Sasvad", "Maharashtra" },
                    { "Satana", "Maharashtra" },
                    { "Satara", "Maharashtra" },
                    { "Sathupalle", "Telangana" },
                    { "Savantvadi", "Maharashtra" },
                    { "Savda", "Maharashtra" },
                    { "Savner", "Maharashtra" },
                    { "Sawari Jawharnagar", "Maharashtra" },
                    { "Secunderabad", "Telangana" },
                    { "Selu", "Maharashtra" },
                    { "Shahada", "Maharashtra" },
                    { "Shahapur", "Maharashtra" },
                    { "Shegaon", "Maharashtra" },
                    { "Shelar", "Maharashtra" },
                    { "Shendurjana", "Maharashtra" },
                    { "Shirdi", "Maharashtra" },
                    { "Shirgaon", "Maharashtra" },
                    { "Shirpur", "Maharashtra" },
                    { "Shirur", "Maharashtra" },
                    { "Shirwal", "Maharashtra" },
                    { "Shivatkar", "Maharashtra" },
                    { "Shrigonda", "Maharashtra" },
                    { "Shrirampur", "Maharashtra" },
                    { "Siddipet", "Telangana" },
                    { "Sillewada", "Maharashtra" },
                    { "Sillod", "Maharashtra" },
                    { "Sindi", "Maharashtra" },
                    { "Sindi Turf Hindnagar", "Maharashtra" },
                    { "Sindkhed Raja", "Maharashtra" },
                    { "Sindkheda", "Maharashtra" },
                    { "Singapur", "Telangana" },
                    { "Sinhgad", "Maharashtra" },
                    { "Sinnar", "Maharashtra" },
                    { "Sircilla", "Telangana" },
                    { "Sirsala", "Maharashtra" },
                    { "Sirur", "Maharashtra" },
                    { "Sita Buldi", "Maharashtra" },
                    { "Skegaon", "Maharashtra" },
                    { "Solapur", "Maharashtra" },
                    { "Sonai", "Maharashtra" },
                    { "Sonala", "Maharashtra" },
                    { "Sonari", "Maharashtra" },
                    { "Songir", "Maharashtra" },
                    { "Soyagaon", "Maharashtra" },
                    { "Srivardhan", "Maharashtra" },
                    { "Sukalwad", "Maharashtra" },
                    { "Sultanpur", "Maharashtra" },
                    { "Surgana", "Maharashtra" },
                    { "Suryapet", "Telangana" },
                    { "Talegaon Dabhade", "Maharashtra" },
                    { "Taloda", "Maharashtra" },
                    { "Taloja", "Maharashtra" },
                    { "Talwade", "Maharashtra" },
                    { "Tandur", "Telangana" },
                    { "Tarapur", "Maharashtra" },
                    { "Tardeo", "Maharashtra" },
                    { "Taroda Nandurbar", "Maharashtra" },
                    { "Tasgaon", "Maharashtra" },
                    { "Tathavade", "Maharashtra" },
                    { "Tekadi", "Maharashtra" },
                    { "Telhara", "Maharashtra" },
                    { "Thane", "Maharashtra" },
                    { "Thane Division", "Maharashtra" },
                    { "Tirira", "Maharashtra" },
                    { "Tirora", "Maharashtra" },
                    { "Tiwasa", "Maharashtra" },
                    { "Trimbak", "Maharashtra" },
                    { "Tuljapur", "Maharashtra" },
                    { "Tumsar", "Maharashtra" },
                    { "Uchgaon", "Maharashtra" },
                    { "Udgir", "Maharashtra" },
                    { "Ulhasnagar", "Maharashtra" },
                    { "Umarga", "Maharashtra" },
                    { "Umarkhed", "Maharashtra" },
                    { "Umarsara", "Maharashtra" },
                    { "Umbar Pada Nandade", "Maharashtra" },
                    { "Umred", "Maharashtra" },
                    { "Umri Pragane Balapur", "Maharashtra" },
                    { "Uran", "Maharashtra" },
                    { "Uran Islampur", "Maharashtra" },
                    { "Utekhol", "Maharashtra" },
                    { "Vadgaon", "Maharashtra" },
                    { "Vadgaon Kasba", "Maharashtra" },
                    { "Vaijapur", "Maharashtra" },
                    { "Vanvadi", "Maharashtra" },
                    { "Varangaon", "Maharashtra" },
                    { "Vasai", "Maharashtra" },
                    { "Vasantnagar", "Maharashtra" },
                    { "Vashind", "Maharashtra" },
                    { "Vemulawada", "Telangana" },
                    { "Vengurla", "Maharashtra" },
                    { "Vikarabad", "Telangana" },
                    { "Virar", "Maharashtra" },
                    { "Vita", "Maharashtra" },
                    { "Vite", "Maharashtra" },
                    { "Vitthalwadi", "Maharashtra" },
                    { "Wadgaon Road", "Maharashtra" },
                    { "Wadi", "Maharashtra" },
                    { "Waghapur", "Maharashtra" },
                    { "Wai", "Maharashtra" },
                    { "Wajegaon", "Maharashtra" },
                    { "Walani", "Maharashtra" },
                    { "Wanaparthy", "Telangana" },
                    { "Wani", "Maharashtra" },
                    { "Warangal", "Telangana" },
                    { "Wardha", "Maharashtra" },
                    { "Warora", "Maharashtra" },
                    { "Warthi", "Maharashtra" },
                    { "Warud", "Maharashtra" },
                    { "Washim", "Maharashtra" },
                    { "Yavatmal", "Maharashtra" },
                    { "Yavatmal Wazaribazar", "Maharashtra" },
                    { "Yellandu", "Telangana" },
                    { "Yeola", "Maharashtra" },
                    { "Yerkheda", "Maharashtra" },
                    { "Zahirabad", "Telangana" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "country_name", "country_phone_code", "country_short_name" },
                values: new object[,]
                {
                    { "Afghanistan", 93, "AF" },
                    { "Albania", 355, "AL" },
                    { "Algeria", 213, "DZ" },
                    { "American Samoa", 1684, "AS" },
                    { "Andorra", 376, "AD" },
                    { "Angola", 244, "AO" },
                    { "Anguilla", 1264, "AI" },
                    { "Antarctica", 0, "AQ" },
                    { "Antigua And Barbuda", 1268, "AG" },
                    { "Argentina", 54, "AR" },
                    { "Armenia", 374, "AM" },
                    { "Aruba", 297, "AW" },
                    { "Australia", 61, "AU" },
                    { "Austria", 43, "AT" },
                    { "Azerbaijan", 994, "AZ" },
                    { "Bahamas The", 1242, "BS" },
                    { "Bahrain", 973, "BH" },
                    { "Bangladesh", 880, "BD" },
                    { "Barbados", 1246, "BB" },
                    { "Belarus", 375, "BY" },
                    { "Belgium", 32, "BE" },
                    { "Belize", 501, "BZ" },
                    { "Benin", 229, "BJ" },
                    { "Bermuda", 1441, "BM" },
                    { "Bhutan", 975, "BT" },
                    { "Bolivia", 591, "BO" },
                    { "Bosnia and Herzegovina", 387, "BA" },
                    { "Botswana", 267, "BW" },
                    { "Bouvet Island", 0, "BV" },
                    { "Brazil", 55, "BR" },
                    { "British Indian Ocean Territory", 246, "IO" },
                    { "Brunei", 673, "BN" },
                    { "Bulgaria", 359, "BG" },
                    { "Burkina Faso", 226, "BF" },
                    { "Burundi", 257, "BI" },
                    { "Cambodia", 855, "KH" },
                    { "Cameroon", 237, "CM" },
                    { "Canada", 1, "CA" },
                    { "Cape Verde", 238, "CV" },
                    { "Cayman Islands", 1345, "KY" },
                    { "Central African Republic", 236, "CF" },
                    { "Chad", 235, "TD" },
                    { "Chile", 56, "CL" },
                    { "China", 86, "CN" },
                    { "Christmas Island", 61, "CX" },
                    { "Cocos (Keeling) Islands", 672, "CC" },
                    { "Colombia", 57, "CO" },
                    { "Comoros", 269, "KM" },
                    { "Cook Islands", 682, "CK" },
                    { "Costa Rica", 506, "CR" },
                    { "Cote D'Ivoire (Ivory Coast)", 225, "CI" },
                    { "Croatia (Hrvatska)", 385, "HR" },
                    { "Cuba", 53, "CU" },
                    { "Cyprus", 357, "CY" },
                    { "Czech Republic", 420, "CZ" },
                    { "Democratic Republic Of The Congo", 243, "CD" },
                    { "Denmark", 45, "DK" },
                    { "Djibouti", 253, "DJ" },
                    { "Dominica", 1767, "DM" },
                    { "Dominican Republic", 1809, "DO" },
                    { "East Timor", 670, "TP" },
                    { "Ecuador", 593, "EC" },
                    { "Egypt", 20, "EG" },
                    { "El Salvador", 503, "SV" },
                    { "Equatorial Guinea", 240, "GQ" },
                    { "Eritrea", 291, "ER" },
                    { "Estonia", 372, "EE" },
                    { "Ethiopia", 251, "ET" },
                    { "Falkland Islands", 500, "FK" },
                    { "Faroe Islands", 298, "FO" },
                    { "Fiji Islands", 679, "FJ" },
                    { "Finland", 358, "FI" },
                    { "France", 33, "FR" },
                    { "French Guiana", 594, "GF" },
                    { "French Polynesia", 689, "PF" },
                    { "French Southern Territories", 0, "TF" },
                    { "Gabon", 241, "GA" },
                    { "Gambia The", 220, "GM" },
                    { "Georgia", 995, "GE" },
                    { "Germany", 49, "DE" },
                    { "Ghana", 233, "GH" },
                    { "Gibraltar", 350, "GI" },
                    { "Greece", 30, "GR" },
                    { "Greenland", 299, "GL" },
                    { "Grenada", 1473, "GD" },
                    { "Guadeloupe", 590, "GP" },
                    { "Guam", 1671, "GU" },
                    { "Guatemala", 502, "GT" },
                    { "Guernsey and Alderney", 44, "XU" },
                    { "Guinea", 224, "GN" },
                    { "Guinea-Bissau", 245, "GW" },
                    { "Guyana", 592, "GY" },
                    { "Haiti", 509, "HT" },
                    { "Heard and McDonald Islands", 0, "HM" },
                    { "Honduras", 504, "HN" },
                    { "Hong Kong S.A.R.", 852, "HK" },
                    { "Hungary", 36, "HU" },
                    { "Iceland", 354, "IS" },
                    { "India", 91, "IN" },
                    { "Indonesia", 62, "ID" },
                    { "Iran", 98, "IR" },
                    { "Iraq", 964, "IQ" },
                    { "Ireland", 353, "IE" },
                    { "Israel", 972, "IL" },
                    { "Italy", 39, "IT" },
                    { "Jamaica", 1876, "JM" },
                    { "Japan", 81, "JP" },
                    { "Jersey", 44, "XJ" },
                    { "Jordan", 962, "JO" },
                    { "Kazakhstan", 7, "KZ" },
                    { "Kenya", 254, "KE" },
                    { "Kiribati", 686, "KI" },
                    { "Korea North", 850, "KP" },
                    { "Korea South", 82, "KR" },
                    { "Kuwait", 965, "KW" },
                    { "Kyrgyzstan", 996, "KG" },
                    { "Laos", 856, "LA" },
                    { "Latvia", 371, "LV" },
                    { "Lebanon", 961, "LB" },
                    { "Lesotho", 266, "LS" },
                    { "Liberia", 231, "LR" },
                    { "Libya", 218, "LY" },
                    { "Liechtenstein", 423, "LI" },
                    { "Lithuania", 370, "LT" },
                    { "Luxembourg", 352, "LU" },
                    { "Macau S.A.R.", 853, "MO" },
                    { "Madagascar", 261, "MG" },
                    { "Malawi", 265, "MW" },
                    { "Malaysia", 60, "MY" },
                    { "Maldives", 960, "MV" },
                    { "Mali", 223, "ML" },
                    { "Malta", 356, "MT" },
                    { "Man (Isle of)", 44, "XM" },
                    { "Marshall Islands", 692, "MH" },
                    { "Martinique", 596, "MQ" },
                    { "Mauritania", 222, "MR" },
                    { "Mauritius", 230, "MU" },
                    { "Mayotte", 269, "YT" },
                    { "Mexico", 52, "MX" },
                    { "Micronesia", 691, "FM" },
                    { "Moldova", 373, "MD" },
                    { "Monaco", 377, "MC" },
                    { "Mongolia", 976, "MN" },
                    { "Montserrat", 1664, "MS" },
                    { "Morocco", 212, "MA" },
                    { "Mozambique", 258, "MZ" },
                    { "Myanmar", 95, "MM" },
                    { "Namibia", 264, "NA" },
                    { "Nauru", 674, "NR" },
                    { "Nepal", 977, "NP" },
                    { "Netherlands Antilles", 599, "AN" },
                    { "Netherlands The", 31, "NL" },
                    { "New Caledonia", 687, "NC" },
                    { "New Zealand", 64, "NZ" },
                    { "Nicaragua", 505, "NI" },
                    { "Niger", 227, "NE" },
                    { "Nigeria", 234, "NG" },
                    { "Niue", 683, "NU" },
                    { "Norfolk Island", 672, "NF" },
                    { "Northern Mariana Islands", 1670, "MP" },
                    { "Norway", 47, "NO" },
                    { "Oman", 968, "OM" },
                    { "Pakistan", 92, "PK" },
                    { "Palau", 680, "PW" },
                    { "Palestinian Territory Occupied", 970, "PS" },
                    { "Panama", 507, "PA" },
                    { "Papua new Guinea", 675, "PG" },
                    { "Paraguay", 595, "PY" },
                    { "Peru", 51, "PE" },
                    { "Philippines", 63, "PH" },
                    { "Pitcairn Island", 0, "PN" },
                    { "Poland", 48, "PL" },
                    { "Portugal", 351, "PT" },
                    { "Puerto Rico", 1787, "PR" },
                    { "Qatar", 974, "QA" },
                    { "Republic Of The Congo", 242, "CG" },
                    { "Reunion", 262, "RE" },
                    { "Romania", 40, "RO" },
                    { "Russia", 70, "RU" },
                    { "Rwanda", 250, "RW" },
                    { "Saint Helena", 290, "SH" },
                    { "Saint Kitts And Nevis", 1869, "KN" },
                    { "Saint Lucia", 1758, "LC" },
                    { "Saint Pierre and Miquelon", 508, "PM" },
                    { "Saint Vincent And The Grenadines", 1784, "VC" },
                    { "Saint-Barthelemy", 590, "BL" },
                    { "Saint-Martin (French part)", 590, "MF" },
                    { "Samoa", 684, "WS" },
                    { "San Marino", 378, "SM" },
                    { "Sao Tome and Principe", 239, "ST" },
                    { "Saudi Arabia", 966, "SA" },
                    { "Senegal", 221, "SN" },
                    { "Serbia", 381, "RS" },
                    { "Seychelles", 248, "SC" },
                    { "Sierra Leone", 232, "SL" },
                    { "Singapore", 65, "SG" },
                    { "Slovakia", 421, "SK" },
                    { "Slovenia", 386, "SI" },
                    { "Solomon Islands", 677, "SB" },
                    { "Somalia", 252, "SO" },
                    { "South Africa", 27, "ZA" },
                    { "South Georgia", 0, "GS" },
                    { "South Sudan", 211, "SS" },
                    { "Spain", 34, "ES" },
                    { "Sri Lanka", 94, "LK" },
                    { "Sudan", 249, "SD" },
                    { "Suriname", 597, "SR" },
                    { "Svalbard And Jan Mayen Islands", 47, "SJ" },
                    { "Swaziland", 268, "SZ" },
                    { "Sweden", 46, "SE" },
                    { "Switzerland", 41, "CH" },
                    { "Syria", 963, "SY" },
                    { "Taiwan", 886, "TW" },
                    { "Tajikistan", 992, "TJ" },
                    { "Tanzania", 255, "TZ" },
                    { "Thailand", 66, "TH" },
                    { "Togo", 228, "TG" },
                    { "Tokelau", 690, "TK" },
                    { "Tonga", 676, "TO" },
                    { "Trinidad And Tobago", 1868, "TT" },
                    { "Tunisia", 216, "TN" },
                    { "Turkey", 90, "TR" },
                    { "Turkmenistan", 7370, "TM" },
                    { "Turks And Caicos Islands", 1649, "TC" },
                    { "Tuvalu", 688, "TV" },
                    { "Uganda", 256, "UG" },
                    { "Ukraine", 380, "UA" },
                    { "United Arab Emirates", 971, "AE" },
                    { "United Kingdom", 44, "GB" },
                    { "United States", 1, "US" },
                    { "United States Minor Outlying Islands", 1, "UM" },
                    { "Uruguay", 598, "UY" },
                    { "Uzbekistan", 998, "UZ" },
                    { "Vanuatu", 678, "VU" },
                    { "Vatican City State (Holy See)", 39, "VA" },
                    { "Venezuela", 58, "VE" },
                    { "Vietnam", 84, "VN" },
                    { "Virgin Islands (British)", 1284, "VG" },
                    { "Virgin Islands (US)", 1340, "VI" },
                    { "Wallis And Futuna Islands", 681, "WF" },
                    { "Western Sahara", 212, "EH" },
                    { "Yemen", 967, "YE" },
                    { "Zambia", 260, "ZM" },
                    { "Zimbabwe", 263, "ZW" }
                });

            migrationBuilder.InsertData(
                table: "States",
                columns: new[] { "state_name", "country_name" },
                values: new object[,]
                {
                    { "Andaman and Nicobar Islands", "India" },
                    { "Andhra Pradesh", "India" },
                    { "Arunachal Pradesh", "India" },
                    { "Assam", "India" },
                    { "Bihar", "India" },
                    { "Chandigarh", "India" },
                    { "Chhattisgarh", "India" },
                    { "Dadra and Nagar Haveli", "India" },
                    { "Daman and Diu", "India" },
                    { "Delhi", "India" },
                    { "Goa", "India" },
                    { "Gujarat", "India" },
                    { "Haryana", "India" },
                    { "Himachal Pradesh", "India" },
                    { "Jammu and Kashmir", "India" },
                    { "Jharkhand", "India" },
                    { "Karnataka", "India" },
                    { "Kerala", "India" },
                    { "Ladakh", "India" },
                    { "Lakshadweep", "India" },
                    { "Madhya Pradesh", "India" },
                    { "Maharashtra", "India" },
                    { "Manipur", "India" },
                    { "Meghalaya", "India" },
                    { "Mizoram", "India" },
                    { "Nagaland", "India" },
                    { "Narora", "India" },
                    { "Odisha", "India" },
                    { "Pondicherry", "India" },
                    { "Punjab", "India" },
                    { "Rajasthan", "India" },
                    { "Sikkim", "India" },
                    { "Tamil Nadu", "India" },
                    { "Telangana", "India" },
                    { "Tripura", "India" },
                    { "Uttar Pradesh", "India" },
                    { "Uttarakhand", "India" },
                    { "West Bengal", "India" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Address_EmployeeId",
                table: "Address",
                column: "EmployeeId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Address");

            migrationBuilder.DropTable(
                name: "Cities");

            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.DropTable(
                name: "Events");

            migrationBuilder.DropTable(
                name: "States");

            migrationBuilder.DropTable(
                name: "Employees");
        }
    }
}
