// <auto-generated />
using System;
using EmployeeAudit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAudit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230731044255_AddingCountryToDB")]
    partial class AddingCountryToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAudit.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("EmployeeAudit.Models.Country", b =>
                {
                    b.Property<string>("country_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("country_phone_code")
                        .HasColumnType("int");

                    b.Property<string>("country_short_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("country_name");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            country_name = "Afghanistan",
                            country_phone_code = 93,
                            country_short_name = "AF"
                        },
                        new
                        {
                            country_name = "Albania",
                            country_phone_code = 355,
                            country_short_name = "AL"
                        },
                        new
                        {
                            country_name = "Algeria",
                            country_phone_code = 213,
                            country_short_name = "DZ"
                        },
                        new
                        {
                            country_name = "American Samoa",
                            country_phone_code = 1684,
                            country_short_name = "AS"
                        },
                        new
                        {
                            country_name = "Andorra",
                            country_phone_code = 376,
                            country_short_name = "AD"
                        },
                        new
                        {
                            country_name = "Angola",
                            country_phone_code = 244,
                            country_short_name = "AO"
                        },
                        new
                        {
                            country_name = "Anguilla",
                            country_phone_code = 1264,
                            country_short_name = "AI"
                        },
                        new
                        {
                            country_name = "Antarctica",
                            country_phone_code = 0,
                            country_short_name = "AQ"
                        },
                        new
                        {
                            country_name = "Antigua And Barbuda",
                            country_phone_code = 1268,
                            country_short_name = "AG"
                        },
                        new
                        {
                            country_name = "Argentina",
                            country_phone_code = 54,
                            country_short_name = "AR"
                        },
                        new
                        {
                            country_name = "Armenia",
                            country_phone_code = 374,
                            country_short_name = "AM"
                        },
                        new
                        {
                            country_name = "Aruba",
                            country_phone_code = 297,
                            country_short_name = "AW"
                        },
                        new
                        {
                            country_name = "Australia",
                            country_phone_code = 61,
                            country_short_name = "AU"
                        },
                        new
                        {
                            country_name = "Austria",
                            country_phone_code = 43,
                            country_short_name = "AT"
                        },
                        new
                        {
                            country_name = "Azerbaijan",
                            country_phone_code = 994,
                            country_short_name = "AZ"
                        },
                        new
                        {
                            country_name = "Bahamas The",
                            country_phone_code = 1242,
                            country_short_name = "BS"
                        },
                        new
                        {
                            country_name = "Bahrain",
                            country_phone_code = 973,
                            country_short_name = "BH"
                        },
                        new
                        {
                            country_name = "Bangladesh",
                            country_phone_code = 880,
                            country_short_name = "BD"
                        },
                        new
                        {
                            country_name = "Barbados",
                            country_phone_code = 1246,
                            country_short_name = "BB"
                        },
                        new
                        {
                            country_name = "Belarus",
                            country_phone_code = 375,
                            country_short_name = "BY"
                        },
                        new
                        {
                            country_name = "Belgium",
                            country_phone_code = 32,
                            country_short_name = "BE"
                        },
                        new
                        {
                            country_name = "Belize",
                            country_phone_code = 501,
                            country_short_name = "BZ"
                        },
                        new
                        {
                            country_name = "Benin",
                            country_phone_code = 229,
                            country_short_name = "BJ"
                        },
                        new
                        {
                            country_name = "Bermuda",
                            country_phone_code = 1441,
                            country_short_name = "BM"
                        },
                        new
                        {
                            country_name = "Bhutan",
                            country_phone_code = 975,
                            country_short_name = "BT"
                        },
                        new
                        {
                            country_name = "Bolivia",
                            country_phone_code = 591,
                            country_short_name = "BO"
                        },
                        new
                        {
                            country_name = "Bosnia and Herzegovina",
                            country_phone_code = 387,
                            country_short_name = "BA"
                        },
                        new
                        {
                            country_name = "Botswana",
                            country_phone_code = 267,
                            country_short_name = "BW"
                        },
                        new
                        {
                            country_name = "Bouvet Island",
                            country_phone_code = 0,
                            country_short_name = "BV"
                        },
                        new
                        {
                            country_name = "Brazil",
                            country_phone_code = 55,
                            country_short_name = "BR"
                        },
                        new
                        {
                            country_name = "British Indian Ocean Territory",
                            country_phone_code = 246,
                            country_short_name = "IO"
                        },
                        new
                        {
                            country_name = "Brunei",
                            country_phone_code = 673,
                            country_short_name = "BN"
                        },
                        new
                        {
                            country_name = "Bulgaria",
                            country_phone_code = 359,
                            country_short_name = "BG"
                        },
                        new
                        {
                            country_name = "Burkina Faso",
                            country_phone_code = 226,
                            country_short_name = "BF"
                        },
                        new
                        {
                            country_name = "Burundi",
                            country_phone_code = 257,
                            country_short_name = "BI"
                        },
                        new
                        {
                            country_name = "Cambodia",
                            country_phone_code = 855,
                            country_short_name = "KH"
                        },
                        new
                        {
                            country_name = "Cameroon",
                            country_phone_code = 237,
                            country_short_name = "CM"
                        },
                        new
                        {
                            country_name = "Canada",
                            country_phone_code = 1,
                            country_short_name = "CA"
                        },
                        new
                        {
                            country_name = "Cape Verde",
                            country_phone_code = 238,
                            country_short_name = "CV"
                        },
                        new
                        {
                            country_name = "Cayman Islands",
                            country_phone_code = 1345,
                            country_short_name = "KY"
                        },
                        new
                        {
                            country_name = "Central African Republic",
                            country_phone_code = 236,
                            country_short_name = "CF"
                        },
                        new
                        {
                            country_name = "Chad",
                            country_phone_code = 235,
                            country_short_name = "TD"
                        },
                        new
                        {
                            country_name = "Chile",
                            country_phone_code = 56,
                            country_short_name = "CL"
                        },
                        new
                        {
                            country_name = "China",
                            country_phone_code = 86,
                            country_short_name = "CN"
                        },
                        new
                        {
                            country_name = "Christmas Island",
                            country_phone_code = 61,
                            country_short_name = "CX"
                        },
                        new
                        {
                            country_name = "Cocos (Keeling) Islands",
                            country_phone_code = 672,
                            country_short_name = "CC"
                        },
                        new
                        {
                            country_name = "Colombia",
                            country_phone_code = 57,
                            country_short_name = "CO"
                        },
                        new
                        {
                            country_name = "Comoros",
                            country_phone_code = 269,
                            country_short_name = "KM"
                        },
                        new
                        {
                            country_name = "Cook Islands",
                            country_phone_code = 682,
                            country_short_name = "CK"
                        },
                        new
                        {
                            country_name = "Costa Rica",
                            country_phone_code = 506,
                            country_short_name = "CR"
                        },
                        new
                        {
                            country_name = "Cote D'Ivoire (Ivory Coast)",
                            country_phone_code = 225,
                            country_short_name = "CI"
                        },
                        new
                        {
                            country_name = "Croatia (Hrvatska)",
                            country_phone_code = 385,
                            country_short_name = "HR"
                        },
                        new
                        {
                            country_name = "Cuba",
                            country_phone_code = 53,
                            country_short_name = "CU"
                        },
                        new
                        {
                            country_name = "Cyprus",
                            country_phone_code = 357,
                            country_short_name = "CY"
                        },
                        new
                        {
                            country_name = "Czech Republic",
                            country_phone_code = 420,
                            country_short_name = "CZ"
                        },
                        new
                        {
                            country_name = "Democratic Republic Of The Congo",
                            country_phone_code = 243,
                            country_short_name = "CD"
                        },
                        new
                        {
                            country_name = "Denmark",
                            country_phone_code = 45,
                            country_short_name = "DK"
                        },
                        new
                        {
                            country_name = "Djibouti",
                            country_phone_code = 253,
                            country_short_name = "DJ"
                        },
                        new
                        {
                            country_name = "Dominica",
                            country_phone_code = 1767,
                            country_short_name = "DM"
                        },
                        new
                        {
                            country_name = "Dominican Republic",
                            country_phone_code = 1809,
                            country_short_name = "DO"
                        },
                        new
                        {
                            country_name = "East Timor",
                            country_phone_code = 670,
                            country_short_name = "TP"
                        },
                        new
                        {
                            country_name = "Ecuador",
                            country_phone_code = 593,
                            country_short_name = "EC"
                        },
                        new
                        {
                            country_name = "Egypt",
                            country_phone_code = 20,
                            country_short_name = "EG"
                        },
                        new
                        {
                            country_name = "El Salvador",
                            country_phone_code = 503,
                            country_short_name = "SV"
                        },
                        new
                        {
                            country_name = "Equatorial Guinea",
                            country_phone_code = 240,
                            country_short_name = "GQ"
                        },
                        new
                        {
                            country_name = "Eritrea",
                            country_phone_code = 291,
                            country_short_name = "ER"
                        },
                        new
                        {
                            country_name = "Estonia",
                            country_phone_code = 372,
                            country_short_name = "EE"
                        },
                        new
                        {
                            country_name = "Ethiopia",
                            country_phone_code = 251,
                            country_short_name = "ET"
                        },
                        new
                        {
                            country_name = "Falkland Islands",
                            country_phone_code = 500,
                            country_short_name = "FK"
                        },
                        new
                        {
                            country_name = "Faroe Islands",
                            country_phone_code = 298,
                            country_short_name = "FO"
                        },
                        new
                        {
                            country_name = "Fiji Islands",
                            country_phone_code = 679,
                            country_short_name = "FJ"
                        },
                        new
                        {
                            country_name = "Finland",
                            country_phone_code = 358,
                            country_short_name = "FI"
                        },
                        new
                        {
                            country_name = "France",
                            country_phone_code = 33,
                            country_short_name = "FR"
                        },
                        new
                        {
                            country_name = "French Guiana",
                            country_phone_code = 594,
                            country_short_name = "GF"
                        },
                        new
                        {
                            country_name = "French Polynesia",
                            country_phone_code = 689,
                            country_short_name = "PF"
                        },
                        new
                        {
                            country_name = "French Southern Territories",
                            country_phone_code = 0,
                            country_short_name = "TF"
                        },
                        new
                        {
                            country_name = "Gabon",
                            country_phone_code = 241,
                            country_short_name = "GA"
                        },
                        new
                        {
                            country_name = "Gambia The",
                            country_phone_code = 220,
                            country_short_name = "GM"
                        },
                        new
                        {
                            country_name = "Georgia",
                            country_phone_code = 995,
                            country_short_name = "GE"
                        },
                        new
                        {
                            country_name = "Germany",
                            country_phone_code = 49,
                            country_short_name = "DE"
                        },
                        new
                        {
                            country_name = "Ghana",
                            country_phone_code = 233,
                            country_short_name = "GH"
                        },
                        new
                        {
                            country_name = "Gibraltar",
                            country_phone_code = 350,
                            country_short_name = "GI"
                        },
                        new
                        {
                            country_name = "Greece",
                            country_phone_code = 30,
                            country_short_name = "GR"
                        },
                        new
                        {
                            country_name = "Greenland",
                            country_phone_code = 299,
                            country_short_name = "GL"
                        },
                        new
                        {
                            country_name = "Grenada",
                            country_phone_code = 1473,
                            country_short_name = "GD"
                        },
                        new
                        {
                            country_name = "Guadeloupe",
                            country_phone_code = 590,
                            country_short_name = "GP"
                        },
                        new
                        {
                            country_name = "Guam",
                            country_phone_code = 1671,
                            country_short_name = "GU"
                        },
                        new
                        {
                            country_name = "Guatemala",
                            country_phone_code = 502,
                            country_short_name = "GT"
                        },
                        new
                        {
                            country_name = "Guernsey and Alderney",
                            country_phone_code = 44,
                            country_short_name = "XU"
                        },
                        new
                        {
                            country_name = "Guinea",
                            country_phone_code = 224,
                            country_short_name = "GN"
                        },
                        new
                        {
                            country_name = "Guinea-Bissau",
                            country_phone_code = 245,
                            country_short_name = "GW"
                        },
                        new
                        {
                            country_name = "Guyana",
                            country_phone_code = 592,
                            country_short_name = "GY"
                        },
                        new
                        {
                            country_name = "Haiti",
                            country_phone_code = 509,
                            country_short_name = "HT"
                        },
                        new
                        {
                            country_name = "Heard and McDonald Islands",
                            country_phone_code = 0,
                            country_short_name = "HM"
                        },
                        new
                        {
                            country_name = "Honduras",
                            country_phone_code = 504,
                            country_short_name = "HN"
                        },
                        new
                        {
                            country_name = "Hong Kong S.A.R.",
                            country_phone_code = 852,
                            country_short_name = "HK"
                        },
                        new
                        {
                            country_name = "Hungary",
                            country_phone_code = 36,
                            country_short_name = "HU"
                        },
                        new
                        {
                            country_name = "Iceland",
                            country_phone_code = 354,
                            country_short_name = "IS"
                        },
                        new
                        {
                            country_name = "India",
                            country_phone_code = 91,
                            country_short_name = "IN"
                        },
                        new
                        {
                            country_name = "Indonesia",
                            country_phone_code = 62,
                            country_short_name = "ID"
                        },
                        new
                        {
                            country_name = "Iran",
                            country_phone_code = 98,
                            country_short_name = "IR"
                        },
                        new
                        {
                            country_name = "Iraq",
                            country_phone_code = 964,
                            country_short_name = "IQ"
                        },
                        new
                        {
                            country_name = "Ireland",
                            country_phone_code = 353,
                            country_short_name = "IE"
                        },
                        new
                        {
                            country_name = "Israel",
                            country_phone_code = 972,
                            country_short_name = "IL"
                        },
                        new
                        {
                            country_name = "Italy",
                            country_phone_code = 39,
                            country_short_name = "IT"
                        },
                        new
                        {
                            country_name = "Jamaica",
                            country_phone_code = 1876,
                            country_short_name = "JM"
                        },
                        new
                        {
                            country_name = "Japan",
                            country_phone_code = 81,
                            country_short_name = "JP"
                        },
                        new
                        {
                            country_name = "Jersey",
                            country_phone_code = 44,
                            country_short_name = "XJ"
                        },
                        new
                        {
                            country_name = "Jordan",
                            country_phone_code = 962,
                            country_short_name = "JO"
                        },
                        new
                        {
                            country_name = "Kazakhstan",
                            country_phone_code = 7,
                            country_short_name = "KZ"
                        },
                        new
                        {
                            country_name = "Kenya",
                            country_phone_code = 254,
                            country_short_name = "KE"
                        },
                        new
                        {
                            country_name = "Kiribati",
                            country_phone_code = 686,
                            country_short_name = "KI"
                        },
                        new
                        {
                            country_name = "Korea North",
                            country_phone_code = 850,
                            country_short_name = "KP"
                        },
                        new
                        {
                            country_name = "Korea South",
                            country_phone_code = 82,
                            country_short_name = "KR"
                        },
                        new
                        {
                            country_name = "Kuwait",
                            country_phone_code = 965,
                            country_short_name = "KW"
                        },
                        new
                        {
                            country_name = "Kyrgyzstan",
                            country_phone_code = 996,
                            country_short_name = "KG"
                        },
                        new
                        {
                            country_name = "Laos",
                            country_phone_code = 856,
                            country_short_name = "LA"
                        },
                        new
                        {
                            country_name = "Latvia",
                            country_phone_code = 371,
                            country_short_name = "LV"
                        },
                        new
                        {
                            country_name = "Lebanon",
                            country_phone_code = 961,
                            country_short_name = "LB"
                        },
                        new
                        {
                            country_name = "Lesotho",
                            country_phone_code = 266,
                            country_short_name = "LS"
                        },
                        new
                        {
                            country_name = "Liberia",
                            country_phone_code = 231,
                            country_short_name = "LR"
                        },
                        new
                        {
                            country_name = "Libya",
                            country_phone_code = 218,
                            country_short_name = "LY"
                        },
                        new
                        {
                            country_name = "Liechtenstein",
                            country_phone_code = 423,
                            country_short_name = "LI"
                        },
                        new
                        {
                            country_name = "Lithuania",
                            country_phone_code = 370,
                            country_short_name = "LT"
                        },
                        new
                        {
                            country_name = "Luxembourg",
                            country_phone_code = 352,
                            country_short_name = "LU"
                        },
                        new
                        {
                            country_name = "Macau S.A.R.",
                            country_phone_code = 853,
                            country_short_name = "MO"
                        },
                        new
                        {
                            country_name = "Madagascar",
                            country_phone_code = 261,
                            country_short_name = "MG"
                        },
                        new
                        {
                            country_name = "Malawi",
                            country_phone_code = 265,
                            country_short_name = "MW"
                        },
                        new
                        {
                            country_name = "Malaysia",
                            country_phone_code = 60,
                            country_short_name = "MY"
                        },
                        new
                        {
                            country_name = "Maldives",
                            country_phone_code = 960,
                            country_short_name = "MV"
                        },
                        new
                        {
                            country_name = "Mali",
                            country_phone_code = 223,
                            country_short_name = "ML"
                        },
                        new
                        {
                            country_name = "Malta",
                            country_phone_code = 356,
                            country_short_name = "MT"
                        },
                        new
                        {
                            country_name = "Man (Isle of)",
                            country_phone_code = 44,
                            country_short_name = "XM"
                        },
                        new
                        {
                            country_name = "Marshall Islands",
                            country_phone_code = 692,
                            country_short_name = "MH"
                        },
                        new
                        {
                            country_name = "Martinique",
                            country_phone_code = 596,
                            country_short_name = "MQ"
                        },
                        new
                        {
                            country_name = "Mauritania",
                            country_phone_code = 222,
                            country_short_name = "MR"
                        },
                        new
                        {
                            country_name = "Mauritius",
                            country_phone_code = 230,
                            country_short_name = "MU"
                        },
                        new
                        {
                            country_name = "Mayotte",
                            country_phone_code = 269,
                            country_short_name = "YT"
                        },
                        new
                        {
                            country_name = "Mexico",
                            country_phone_code = 52,
                            country_short_name = "MX"
                        },
                        new
                        {
                            country_name = "Micronesia",
                            country_phone_code = 691,
                            country_short_name = "FM"
                        },
                        new
                        {
                            country_name = "Moldova",
                            country_phone_code = 373,
                            country_short_name = "MD"
                        },
                        new
                        {
                            country_name = "Monaco",
                            country_phone_code = 377,
                            country_short_name = "MC"
                        },
                        new
                        {
                            country_name = "Mongolia",
                            country_phone_code = 976,
                            country_short_name = "MN"
                        },
                        new
                        {
                            country_name = "Montserrat",
                            country_phone_code = 1664,
                            country_short_name = "MS"
                        },
                        new
                        {
                            country_name = "Morocco",
                            country_phone_code = 212,
                            country_short_name = "MA"
                        },
                        new
                        {
                            country_name = "Mozambique",
                            country_phone_code = 258,
                            country_short_name = "MZ"
                        },
                        new
                        {
                            country_name = "Myanmar",
                            country_phone_code = 95,
                            country_short_name = "MM"
                        },
                        new
                        {
                            country_name = "Namibia",
                            country_phone_code = 264,
                            country_short_name = "NA"
                        },
                        new
                        {
                            country_name = "Nauru",
                            country_phone_code = 674,
                            country_short_name = "NR"
                        },
                        new
                        {
                            country_name = "Nepal",
                            country_phone_code = 977,
                            country_short_name = "NP"
                        },
                        new
                        {
                            country_name = "Netherlands Antilles",
                            country_phone_code = 599,
                            country_short_name = "AN"
                        },
                        new
                        {
                            country_name = "Netherlands The",
                            country_phone_code = 31,
                            country_short_name = "NL"
                        },
                        new
                        {
                            country_name = "New Caledonia",
                            country_phone_code = 687,
                            country_short_name = "NC"
                        },
                        new
                        {
                            country_name = "New Zealand",
                            country_phone_code = 64,
                            country_short_name = "NZ"
                        },
                        new
                        {
                            country_name = "Nicaragua",
                            country_phone_code = 505,
                            country_short_name = "NI"
                        },
                        new
                        {
                            country_name = "Niger",
                            country_phone_code = 227,
                            country_short_name = "NE"
                        },
                        new
                        {
                            country_name = "Nigeria",
                            country_phone_code = 234,
                            country_short_name = "NG"
                        },
                        new
                        {
                            country_name = "Niue",
                            country_phone_code = 683,
                            country_short_name = "NU"
                        },
                        new
                        {
                            country_name = "Norfolk Island",
                            country_phone_code = 672,
                            country_short_name = "NF"
                        },
                        new
                        {
                            country_name = "Northern Mariana Islands",
                            country_phone_code = 1670,
                            country_short_name = "MP"
                        },
                        new
                        {
                            country_name = "Norway",
                            country_phone_code = 47,
                            country_short_name = "NO"
                        },
                        new
                        {
                            country_name = "Oman",
                            country_phone_code = 968,
                            country_short_name = "OM"
                        },
                        new
                        {
                            country_name = "Pakistan",
                            country_phone_code = 92,
                            country_short_name = "PK"
                        },
                        new
                        {
                            country_name = "Palau",
                            country_phone_code = 680,
                            country_short_name = "PW"
                        },
                        new
                        {
                            country_name = "Palestinian Territory Occupied",
                            country_phone_code = 970,
                            country_short_name = "PS"
                        },
                        new
                        {
                            country_name = "Panama",
                            country_phone_code = 507,
                            country_short_name = "PA"
                        },
                        new
                        {
                            country_name = "Papua new Guinea",
                            country_phone_code = 675,
                            country_short_name = "PG"
                        },
                        new
                        {
                            country_name = "Paraguay",
                            country_phone_code = 595,
                            country_short_name = "PY"
                        },
                        new
                        {
                            country_name = "Peru",
                            country_phone_code = 51,
                            country_short_name = "PE"
                        },
                        new
                        {
                            country_name = "Philippines",
                            country_phone_code = 63,
                            country_short_name = "PH"
                        },
                        new
                        {
                            country_name = "Pitcairn Island",
                            country_phone_code = 0,
                            country_short_name = "PN"
                        },
                        new
                        {
                            country_name = "Poland",
                            country_phone_code = 48,
                            country_short_name = "PL"
                        },
                        new
                        {
                            country_name = "Portugal",
                            country_phone_code = 351,
                            country_short_name = "PT"
                        },
                        new
                        {
                            country_name = "Puerto Rico",
                            country_phone_code = 1787,
                            country_short_name = "PR"
                        },
                        new
                        {
                            country_name = "Qatar",
                            country_phone_code = 974,
                            country_short_name = "QA"
                        },
                        new
                        {
                            country_name = "Republic Of The Congo",
                            country_phone_code = 242,
                            country_short_name = "CG"
                        },
                        new
                        {
                            country_name = "Reunion",
                            country_phone_code = 262,
                            country_short_name = "RE"
                        },
                        new
                        {
                            country_name = "Romania",
                            country_phone_code = 40,
                            country_short_name = "RO"
                        },
                        new
                        {
                            country_name = "Russia",
                            country_phone_code = 70,
                            country_short_name = "RU"
                        },
                        new
                        {
                            country_name = "Rwanda",
                            country_phone_code = 250,
                            country_short_name = "RW"
                        },
                        new
                        {
                            country_name = "Saint Helena",
                            country_phone_code = 290,
                            country_short_name = "SH"
                        },
                        new
                        {
                            country_name = "Saint Kitts And Nevis",
                            country_phone_code = 1869,
                            country_short_name = "KN"
                        },
                        new
                        {
                            country_name = "Saint Lucia",
                            country_phone_code = 1758,
                            country_short_name = "LC"
                        },
                        new
                        {
                            country_name = "Saint Pierre and Miquelon",
                            country_phone_code = 508,
                            country_short_name = "PM"
                        },
                        new
                        {
                            country_name = "Saint Vincent And The Grenadines",
                            country_phone_code = 1784,
                            country_short_name = "VC"
                        },
                        new
                        {
                            country_name = "Saint-Barthelemy",
                            country_phone_code = 590,
                            country_short_name = "BL"
                        },
                        new
                        {
                            country_name = "Saint-Martin (French part)",
                            country_phone_code = 590,
                            country_short_name = "MF"
                        },
                        new
                        {
                            country_name = "Samoa",
                            country_phone_code = 684,
                            country_short_name = "WS"
                        },
                        new
                        {
                            country_name = "San Marino",
                            country_phone_code = 378,
                            country_short_name = "SM"
                        },
                        new
                        {
                            country_name = "Sao Tome and Principe",
                            country_phone_code = 239,
                            country_short_name = "ST"
                        },
                        new
                        {
                            country_name = "Saudi Arabia",
                            country_phone_code = 966,
                            country_short_name = "SA"
                        },
                        new
                        {
                            country_name = "Senegal",
                            country_phone_code = 221,
                            country_short_name = "SN"
                        },
                        new
                        {
                            country_name = "Serbia",
                            country_phone_code = 381,
                            country_short_name = "RS"
                        },
                        new
                        {
                            country_name = "Seychelles",
                            country_phone_code = 248,
                            country_short_name = "SC"
                        },
                        new
                        {
                            country_name = "Sierra Leone",
                            country_phone_code = 232,
                            country_short_name = "SL"
                        },
                        new
                        {
                            country_name = "Singapore",
                            country_phone_code = 65,
                            country_short_name = "SG"
                        },
                        new
                        {
                            country_name = "Slovakia",
                            country_phone_code = 421,
                            country_short_name = "SK"
                        },
                        new
                        {
                            country_name = "Slovenia",
                            country_phone_code = 386,
                            country_short_name = "SI"
                        },
                        new
                        {
                            country_name = "Solomon Islands",
                            country_phone_code = 677,
                            country_short_name = "SB"
                        },
                        new
                        {
                            country_name = "Somalia",
                            country_phone_code = 252,
                            country_short_name = "SO"
                        },
                        new
                        {
                            country_name = "South Africa",
                            country_phone_code = 27,
                            country_short_name = "ZA"
                        },
                        new
                        {
                            country_name = "South Georgia",
                            country_phone_code = 0,
                            country_short_name = "GS"
                        },
                        new
                        {
                            country_name = "South Sudan",
                            country_phone_code = 211,
                            country_short_name = "SS"
                        },
                        new
                        {
                            country_name = "Spain",
                            country_phone_code = 34,
                            country_short_name = "ES"
                        },
                        new
                        {
                            country_name = "Sri Lanka",
                            country_phone_code = 94,
                            country_short_name = "LK"
                        },
                        new
                        {
                            country_name = "Sudan",
                            country_phone_code = 249,
                            country_short_name = "SD"
                        },
                        new
                        {
                            country_name = "Suriname",
                            country_phone_code = 597,
                            country_short_name = "SR"
                        },
                        new
                        {
                            country_name = "Svalbard And Jan Mayen Islands",
                            country_phone_code = 47,
                            country_short_name = "SJ"
                        },
                        new
                        {
                            country_name = "Swaziland",
                            country_phone_code = 268,
                            country_short_name = "SZ"
                        },
                        new
                        {
                            country_name = "Sweden",
                            country_phone_code = 46,
                            country_short_name = "SE"
                        },
                        new
                        {
                            country_name = "Switzerland",
                            country_phone_code = 41,
                            country_short_name = "CH"
                        },
                        new
                        {
                            country_name = "Syria",
                            country_phone_code = 963,
                            country_short_name = "SY"
                        },
                        new
                        {
                            country_name = "Taiwan",
                            country_phone_code = 886,
                            country_short_name = "TW"
                        },
                        new
                        {
                            country_name = "Tajikistan",
                            country_phone_code = 992,
                            country_short_name = "TJ"
                        },
                        new
                        {
                            country_name = "Tanzania",
                            country_phone_code = 255,
                            country_short_name = "TZ"
                        },
                        new
                        {
                            country_name = "Thailand",
                            country_phone_code = 66,
                            country_short_name = "TH"
                        },
                        new
                        {
                            country_name = "Togo",
                            country_phone_code = 228,
                            country_short_name = "TG"
                        },
                        new
                        {
                            country_name = "Tokelau",
                            country_phone_code = 690,
                            country_short_name = "TK"
                        },
                        new
                        {
                            country_name = "Tonga",
                            country_phone_code = 676,
                            country_short_name = "TO"
                        },
                        new
                        {
                            country_name = "Trinidad And Tobago",
                            country_phone_code = 1868,
                            country_short_name = "TT"
                        },
                        new
                        {
                            country_name = "Tunisia",
                            country_phone_code = 216,
                            country_short_name = "TN"
                        },
                        new
                        {
                            country_name = "Turkey",
                            country_phone_code = 90,
                            country_short_name = "TR"
                        },
                        new
                        {
                            country_name = "Turkmenistan",
                            country_phone_code = 7370,
                            country_short_name = "TM"
                        },
                        new
                        {
                            country_name = "Turks And Caicos Islands",
                            country_phone_code = 1649,
                            country_short_name = "TC"
                        },
                        new
                        {
                            country_name = "Tuvalu",
                            country_phone_code = 688,
                            country_short_name = "TV"
                        },
                        new
                        {
                            country_name = "Uganda",
                            country_phone_code = 256,
                            country_short_name = "UG"
                        },
                        new
                        {
                            country_name = "Ukraine",
                            country_phone_code = 380,
                            country_short_name = "UA"
                        },
                        new
                        {
                            country_name = "United Arab Emirates",
                            country_phone_code = 971,
                            country_short_name = "AE"
                        },
                        new
                        {
                            country_name = "United Kingdom",
                            country_phone_code = 44,
                            country_short_name = "GB"
                        },
                        new
                        {
                            country_name = "United States",
                            country_phone_code = 1,
                            country_short_name = "US"
                        },
                        new
                        {
                            country_name = "United States Minor Outlying Islands",
                            country_phone_code = 1,
                            country_short_name = "UM"
                        },
                        new
                        {
                            country_name = "Uruguay",
                            country_phone_code = 598,
                            country_short_name = "UY"
                        },
                        new
                        {
                            country_name = "Uzbekistan",
                            country_phone_code = 998,
                            country_short_name = "UZ"
                        },
                        new
                        {
                            country_name = "Vanuatu",
                            country_phone_code = 678,
                            country_short_name = "VU"
                        },
                        new
                        {
                            country_name = "Vatican City State (Holy See)",
                            country_phone_code = 39,
                            country_short_name = "VA"
                        },
                        new
                        {
                            country_name = "Venezuela",
                            country_phone_code = 58,
                            country_short_name = "VE"
                        },
                        new
                        {
                            country_name = "Vietnam",
                            country_phone_code = 84,
                            country_short_name = "VN"
                        },
                        new
                        {
                            country_name = "Virgin Islands (British)",
                            country_phone_code = 1284,
                            country_short_name = "VG"
                        },
                        new
                        {
                            country_name = "Virgin Islands (US)",
                            country_phone_code = 1340,
                            country_short_name = "VI"
                        },
                        new
                        {
                            country_name = "Wallis And Futuna Islands",
                            country_phone_code = 681,
                            country_short_name = "WF"
                        },
                        new
                        {
                            country_name = "Western Sahara",
                            country_phone_code = 212,
                            country_short_name = "EH"
                        },
                        new
                        {
                            country_name = "Yemen",
                            country_phone_code = 967,
                            country_short_name = "YE"
                        },
                        new
                        {
                            country_name = "Zambia",
                            country_phone_code = 260,
                            country_short_name = "ZM"
                        },
                        new
                        {
                            country_name = "Zimbabwe",
                            country_phone_code = 263,
                            country_short_name = "ZW"
                        });
                });

            modelBuilder.Entity("EmployeeAudit.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeAudit.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EmployeeAudit.Models.Address", b =>
                {
                    b.HasOne("EmployeeAudit.Models.Employee", null)
                        .WithOne("Address")
                        .HasForeignKey("EmployeeAudit.Models.Address", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeAudit.Models.Employee", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
