using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace EmployeeAudit.Migrations
{
    /// <inheritdoc />
    public partial class AddingCountryToDB : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Employees",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    country_name = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    country_short_name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    country_phone_code = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.country_name);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "country_name", "country_phone_code", "country_short_name" },
                values: new object[,]
                {
                    { "Afghanistan", 93, "AF" },
                    { "Albania", 355, "AL" },
                    { "Algeria", 213, "DZ" },
                    { "American Samoa", 1684, "AS" },
                    { "Andorra", 376, "AD" },
                    { "Angola", 244, "AO" },
                    { "Anguilla", 1264, "AI" },
                    { "Antarctica", 0, "AQ" },
                    { "Antigua And Barbuda", 1268, "AG" },
                    { "Argentina", 54, "AR" },
                    { "Armenia", 374, "AM" },
                    { "Aruba", 297, "AW" },
                    { "Australia", 61, "AU" },
                    { "Austria", 43, "AT" },
                    { "Azerbaijan", 994, "AZ" },
                    { "Bahamas The", 1242, "BS" },
                    { "Bahrain", 973, "BH" },
                    { "Bangladesh", 880, "BD" },
                    { "Barbados", 1246, "BB" },
                    { "Belarus", 375, "BY" },
                    { "Belgium", 32, "BE" },
                    { "Belize", 501, "BZ" },
                    { "Benin", 229, "BJ" },
                    { "Bermuda", 1441, "BM" },
                    { "Bhutan", 975, "BT" },
                    { "Bolivia", 591, "BO" },
                    { "Bosnia and Herzegovina", 387, "BA" },
                    { "Botswana", 267, "BW" },
                    { "Bouvet Island", 0, "BV" },
                    { "Brazil", 55, "BR" },
                    { "British Indian Ocean Territory", 246, "IO" },
                    { "Brunei", 673, "BN" },
                    { "Bulgaria", 359, "BG" },
                    { "Burkina Faso", 226, "BF" },
                    { "Burundi", 257, "BI" },
                    { "Cambodia", 855, "KH" },
                    { "Cameroon", 237, "CM" },
                    { "Canada", 1, "CA" },
                    { "Cape Verde", 238, "CV" },
                    { "Cayman Islands", 1345, "KY" },
                    { "Central African Republic", 236, "CF" },
                    { "Chad", 235, "TD" },
                    { "Chile", 56, "CL" },
                    { "China", 86, "CN" },
                    { "Christmas Island", 61, "CX" },
                    { "Cocos (Keeling) Islands", 672, "CC" },
                    { "Colombia", 57, "CO" },
                    { "Comoros", 269, "KM" },
                    { "Cook Islands", 682, "CK" },
                    { "Costa Rica", 506, "CR" },
                    { "Cote D'Ivoire (Ivory Coast)", 225, "CI" },
                    { "Croatia (Hrvatska)", 385, "HR" },
                    { "Cuba", 53, "CU" },
                    { "Cyprus", 357, "CY" },
                    { "Czech Republic", 420, "CZ" },
                    { "Democratic Republic Of The Congo", 243, "CD" },
                    { "Denmark", 45, "DK" },
                    { "Djibouti", 253, "DJ" },
                    { "Dominica", 1767, "DM" },
                    { "Dominican Republic", 1809, "DO" },
                    { "East Timor", 670, "TP" },
                    { "Ecuador", 593, "EC" },
                    { "Egypt", 20, "EG" },
                    { "El Salvador", 503, "SV" },
                    { "Equatorial Guinea", 240, "GQ" },
                    { "Eritrea", 291, "ER" },
                    { "Estonia", 372, "EE" },
                    { "Ethiopia", 251, "ET" },
                    { "Falkland Islands", 500, "FK" },
                    { "Faroe Islands", 298, "FO" },
                    { "Fiji Islands", 679, "FJ" },
                    { "Finland", 358, "FI" },
                    { "France", 33, "FR" },
                    { "French Guiana", 594, "GF" },
                    { "French Polynesia", 689, "PF" },
                    { "French Southern Territories", 0, "TF" },
                    { "Gabon", 241, "GA" },
                    { "Gambia The", 220, "GM" },
                    { "Georgia", 995, "GE" },
                    { "Germany", 49, "DE" },
                    { "Ghana", 233, "GH" },
                    { "Gibraltar", 350, "GI" },
                    { "Greece", 30, "GR" },
                    { "Greenland", 299, "GL" },
                    { "Grenada", 1473, "GD" },
                    { "Guadeloupe", 590, "GP" },
                    { "Guam", 1671, "GU" },
                    { "Guatemala", 502, "GT" },
                    { "Guernsey and Alderney", 44, "XU" },
                    { "Guinea", 224, "GN" },
                    { "Guinea-Bissau", 245, "GW" },
                    { "Guyana", 592, "GY" },
                    { "Haiti", 509, "HT" },
                    { "Heard and McDonald Islands", 0, "HM" },
                    { "Honduras", 504, "HN" },
                    { "Hong Kong S.A.R.", 852, "HK" },
                    { "Hungary", 36, "HU" },
                    { "Iceland", 354, "IS" },
                    { "India", 91, "IN" },
                    { "Indonesia", 62, "ID" },
                    { "Iran", 98, "IR" },
                    { "Iraq", 964, "IQ" },
                    { "Ireland", 353, "IE" },
                    { "Israel", 972, "IL" },
                    { "Italy", 39, "IT" },
                    { "Jamaica", 1876, "JM" },
                    { "Japan", 81, "JP" },
                    { "Jersey", 44, "XJ" },
                    { "Jordan", 962, "JO" },
                    { "Kazakhstan", 7, "KZ" },
                    { "Kenya", 254, "KE" },
                    { "Kiribati", 686, "KI" },
                    { "Korea North", 850, "KP" },
                    { "Korea South", 82, "KR" },
                    { "Kuwait", 965, "KW" },
                    { "Kyrgyzstan", 996, "KG" },
                    { "Laos", 856, "LA" },
                    { "Latvia", 371, "LV" },
                    { "Lebanon", 961, "LB" },
                    { "Lesotho", 266, "LS" },
                    { "Liberia", 231, "LR" },
                    { "Libya", 218, "LY" },
                    { "Liechtenstein", 423, "LI" },
                    { "Lithuania", 370, "LT" },
                    { "Luxembourg", 352, "LU" },
                    { "Macau S.A.R.", 853, "MO" },
                    { "Madagascar", 261, "MG" },
                    { "Malawi", 265, "MW" },
                    { "Malaysia", 60, "MY" },
                    { "Maldives", 960, "MV" },
                    { "Mali", 223, "ML" },
                    { "Malta", 356, "MT" },
                    { "Man (Isle of)", 44, "XM" },
                    { "Marshall Islands", 692, "MH" },
                    { "Martinique", 596, "MQ" },
                    { "Mauritania", 222, "MR" },
                    { "Mauritius", 230, "MU" },
                    { "Mayotte", 269, "YT" },
                    { "Mexico", 52, "MX" },
                    { "Micronesia", 691, "FM" },
                    { "Moldova", 373, "MD" },
                    { "Monaco", 377, "MC" },
                    { "Mongolia", 976, "MN" },
                    { "Montserrat", 1664, "MS" },
                    { "Morocco", 212, "MA" },
                    { "Mozambique", 258, "MZ" },
                    { "Myanmar", 95, "MM" },
                    { "Namibia", 264, "NA" },
                    { "Nauru", 674, "NR" },
                    { "Nepal", 977, "NP" },
                    { "Netherlands Antilles", 599, "AN" },
                    { "Netherlands The", 31, "NL" },
                    { "New Caledonia", 687, "NC" },
                    { "New Zealand", 64, "NZ" },
                    { "Nicaragua", 505, "NI" },
                    { "Niger", 227, "NE" },
                    { "Nigeria", 234, "NG" },
                    { "Niue", 683, "NU" },
                    { "Norfolk Island", 672, "NF" },
                    { "Northern Mariana Islands", 1670, "MP" },
                    { "Norway", 47, "NO" },
                    { "Oman", 968, "OM" },
                    { "Pakistan", 92, "PK" },
                    { "Palau", 680, "PW" },
                    { "Palestinian Territory Occupied", 970, "PS" },
                    { "Panama", 507, "PA" },
                    { "Papua new Guinea", 675, "PG" },
                    { "Paraguay", 595, "PY" },
                    { "Peru", 51, "PE" },
                    { "Philippines", 63, "PH" },
                    { "Pitcairn Island", 0, "PN" },
                    { "Poland", 48, "PL" },
                    { "Portugal", 351, "PT" },
                    { "Puerto Rico", 1787, "PR" },
                    { "Qatar", 974, "QA" },
                    { "Republic Of The Congo", 242, "CG" },
                    { "Reunion", 262, "RE" },
                    { "Romania", 40, "RO" },
                    { "Russia", 70, "RU" },
                    { "Rwanda", 250, "RW" },
                    { "Saint Helena", 290, "SH" },
                    { "Saint Kitts And Nevis", 1869, "KN" },
                    { "Saint Lucia", 1758, "LC" },
                    { "Saint Pierre and Miquelon", 508, "PM" },
                    { "Saint Vincent And The Grenadines", 1784, "VC" },
                    { "Saint-Barthelemy", 590, "BL" },
                    { "Saint-Martin (French part)", 590, "MF" },
                    { "Samoa", 684, "WS" },
                    { "San Marino", 378, "SM" },
                    { "Sao Tome and Principe", 239, "ST" },
                    { "Saudi Arabia", 966, "SA" },
                    { "Senegal", 221, "SN" },
                    { "Serbia", 381, "RS" },
                    { "Seychelles", 248, "SC" },
                    { "Sierra Leone", 232, "SL" },
                    { "Singapore", 65, "SG" },
                    { "Slovakia", 421, "SK" },
                    { "Slovenia", 386, "SI" },
                    { "Solomon Islands", 677, "SB" },
                    { "Somalia", 252, "SO" },
                    { "South Africa", 27, "ZA" },
                    { "South Georgia", 0, "GS" },
                    { "South Sudan", 211, "SS" },
                    { "Spain", 34, "ES" },
                    { "Sri Lanka", 94, "LK" },
                    { "Sudan", 249, "SD" },
                    { "Suriname", 597, "SR" },
                    { "Svalbard And Jan Mayen Islands", 47, "SJ" },
                    { "Swaziland", 268, "SZ" },
                    { "Sweden", 46, "SE" },
                    { "Switzerland", 41, "CH" },
                    { "Syria", 963, "SY" },
                    { "Taiwan", 886, "TW" },
                    { "Tajikistan", 992, "TJ" },
                    { "Tanzania", 255, "TZ" },
                    { "Thailand", 66, "TH" },
                    { "Togo", 228, "TG" },
                    { "Tokelau", 690, "TK" },
                    { "Tonga", 676, "TO" },
                    { "Trinidad And Tobago", 1868, "TT" },
                    { "Tunisia", 216, "TN" },
                    { "Turkey", 90, "TR" },
                    { "Turkmenistan", 7370, "TM" },
                    { "Turks And Caicos Islands", 1649, "TC" },
                    { "Tuvalu", 688, "TV" },
                    { "Uganda", 256, "UG" },
                    { "Ukraine", 380, "UA" },
                    { "United Arab Emirates", 971, "AE" },
                    { "United Kingdom", 44, "GB" },
                    { "United States", 1, "US" },
                    { "United States Minor Outlying Islands", 1, "UM" },
                    { "Uruguay", 598, "UY" },
                    { "Uzbekistan", 998, "UZ" },
                    { "Vanuatu", 678, "VU" },
                    { "Vatican City State (Holy See)", 39, "VA" },
                    { "Venezuela", 58, "VE" },
                    { "Vietnam", 84, "VN" },
                    { "Virgin Islands (British)", 1284, "VG" },
                    { "Virgin Islands (US)", 1340, "VI" },
                    { "Wallis And Futuna Islands", 681, "WF" },
                    { "Western Sahara", 212, "EH" },
                    { "Yemen", 967, "YE" },
                    { "Zambia", 260, "ZM" },
                    { "Zimbabwe", 263, "ZW" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(100)",
                oldMaxLength: 100);
        }
    }
}
